config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games do
    resources :reviews
  end
  root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :games
end

app/models/game.rb
class Game < ApplicationRecord

    belongs_to :user
    belongs_to :category
    has_many :reviews

    #accesing the image
    has_attached_file :game_img, styles: { game_index: "250x350>", game_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :game_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :game
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    require 'httparty'
    #these happen before anything else occurs
    before_action :find_game, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def index
        if params[:category].blank?
            #display games in descending order
            @games = Game.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @games = Game.where(:category_id => @category_id).order("created_at DESC")
        end

        #List of free to play PC games from https://github.com/public-apis/public-apis
        response = HTTParty.get("https://www.freetogame.com/api/games?platform=pc")
        responseLoopString = response[0]["title"] if response.code == 200 

        for apiloop in 1..100
            responseLoop = response[apiloop]["title"] if response.code == 200
            responseLoopString = responseLoopString + ", " + responseLoop
        end

        @httpresponse2 = responseLoopString

        #pulling news for specific game pages using steam app ID
        response = HTTParty.get("https://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?appid=594650&count=3&maxlength=300&format=json")
        @httpresponse = response.parsed_response["appnews"]["newsitems"] if response.code == 200

        
    end   

    def new
        @game = current_user.games.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def show
    end

    def create
        @game = current_user.games.build(game_params)
        @game.category_id = params[:category_id]

        #redirect to correct pages based off actions
        if @game.save
            redirect_to root_path
        else 
            render 'new'
        end
    end

    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        #update category too
        @game.category_id = params[:category_id]
        #saving the new information
        if @game.update(game_params)
            redirect_to game_path(@game)
        else
            render 'edit'
        end
    end

    def destroy
        @game.destroy
        redirect_to root_path
    end

    private 

        #take in game parameters
        def game_params
            params.require(:game).permit(:title, :description, :releaseYear, :category_id, :game_img)
        end

        #find game params by using game id to show them when you edit
        def find_game
            @game = Game.find(params[:id])
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_game
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.game_id = @game.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to game_path(@game)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        
        if @review.update(review_params)
            redirect_to game_path(@game)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to game_path(@game)
    end

    private

        def review_params
            params.require(:review).permit(:rating, :comment)
        end

        def find_game
            @game = Game.find(params[:game_id])
        end

        def find_review
            @review = Review.find(params[:id])
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game, :html => { :multipart => true} do |f| %>

    <div style="padding-top:10px">
        <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
    </div>

    <div style="padding-top:10px">
        <%= f.file_field :game_img%>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :title, label: "Game Title"%></h3>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :description%></h3>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :releaseYear, label:"Release Year"%></h3>
    </div>

    <div style="padding-top:10px">
        <%= f.button :submit, class: 'submit-button' %>
    </div>
<% end %>

app/views/games/edit.html.erb

<h1>Edit Game</h1>

<%= simple_form_for @game, :html => {  :multipart => true} do |f| %>

    <div style="padding-top:10px">
        <%= f.select :category_id, @categories %>
    </div>

    <div style="padding-top:10px">
        <%= f.file_field :game_img%>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :title, label: "Game Title"%></h3>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :description%></h3>
    </div>

    <div style="padding-top:10px">
        <h3><%= f.input :releaseYear, label:"Release Year"%></h3>
    </div>

    <div style="padding-top:10px">
        <%= f.button :submit, class: 'submit-button' %>
    </div>
<% end %>

app/views/games/index.html.erb
<h1 class="current-category" style="font-weight:bold"><%= params[:category] %></h1>

<% if @games.count == 0 %>
    
    <h2>There are currently no games for this category</h2>
<% else %>
    <div style="padding-top:10px" class="row">

        <% @games.each do |game| %>    

            <div class="col-md-3">

                <a href="/games/<%= game.id %>">
                    <%= image_tag game.game_img.url(:game_index), class: "game" %>
                </a>
                <h2 ><%= link_to game.title, game_path(game), class:"normal-link" %></h2>

    	    </div>

        <% end %>

        
    </div>
<% end %>
</br>
</br>
</br>
<p><b>List of free to play PC games</b></p>
<p><%= @httpresponse2 %></p>
<p><b>Steam game news</b></p>
<p><%= @httpresponse %></p>




app/views/games/new.html.erb

    <h1 style="font-weight:bold">New Review</h1>

    <%= render 'form' %>

app/views/games/show.html.erb

<div class="row">

    <div class="col-md-4">
        <%= image_tag @game.game_img.url(:game_show), class: "game-show" %>
    </div>
    
    <div class="col-md-8">
        <h1 style="font-weight:bold"><%= @game.title %></h1>
        <h3>Genre: <%= @game.category.name%></h3>

        <div style="padding-top:10px">
            <p style="font-size:20px"><%= @game.description%></p>
        </div>
        <p>Released in <%= @game.releaseYear %></p>
    </div>

</div>

<div class="row">
    <div class="col-md-4">

        <%= render @game.reviews %>

        <div style="padding-top:30px">
            <%= link_to "Add Review", new_game_review_path(@game) %>
        </div>

    </div>
</div>

<div style="padding-top:30px">
    <%= link_to "Back", root_path %>

    <% if user_signed_in?%>
        <% if @game.user_id == current_user.id %>
            <%= link_to "Edit", edit_game_path(@game) %>
            <%= link_to "Delete", game_path(@game), method: :delete, data: { confirm: "Are you sure?"}%>
        <% end %>
    <% end %>
</div>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
          <div class="navbar-header bold-letters">
              <%= link_to "Game Review", root_path, class: "navbar-brand" %>          
          </div>
          
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>
                  <li class="nav-link active"><%= link_to "Add Game", new_game_path, class: "normal-link normal-link:hover"%></li>
                <% end %>
            </ul>

            <ul class="nav navbar-nav">
                <li class="dropdown nav-link active" style="padding-left:10px">
                  <a class="nav-link dropdown-toggle bold-letters" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">Genres</a>
                  <ul class="dropdown-menu" role="menu">
                      <% Category.all.each do |category| %>
                          <li class="<%= 'active' if params[:category] == category.name %>">
                            <%= link_to category.name, games_path(category: category.name), class: "link normal-link normal-link:hover" %>
                          </li>
                      <% end %>
                  </ul>
                </li>

                <li class="nav-link active" style="padding-top:15px"><%= link_to "Sign Up", new_user_registration_path, class: "normal-link normal-link:hover" %></li>
                <% if user_signed_in? %>
                    <li style="padding-left:10px; padding-top:15px" class="nav-link active"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "normal-link normal-link:hover" %></li>
                <% else %>
                    <li style="padding-left:10px; padding-top:15px" class="nav-link active"><%= link_to "Log In", new_user_session_path, class: "normal-link normal-link:hover" %></li>
                <% end %>         
            </ul>

            
          
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@game, @game.reviews.build]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment%>
    <%= f.button :submit%>
<% end %>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.comment %></p>

<% if user_signed_in? %>

    <% if review.user_id == current_user.id %>

        <%= link_to "Edit", edit_game_review_path(review.game, review) %>
        <%= link_to "Delete", game_review_path(review.game, review), method: :delete, data: {confirm: "Are you sure?"} %>

    <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@game, @review]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>